# Generated by Django 4.0.5 on 2022-06-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
