# Generated by Django 4.0.5 on 2022-06-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_topic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='level',
            field=models.IntegerField(blank=True),
        ),
    ]
