# Generated by Django 4.0.5 on 2022-06-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_order_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courses',
        ),
        migrations.AddField(
            model_name='order',
            name='courses',
            field=models.ManyToManyField(to='myapp.course'),
        ),
    ]
